node {
    def mvnHome
    stage('Preparation') { // for display purposes
        // Get some code from a GitHub repository
        git 'https://github.com/dannmatt/maven-simple-project.git'
        // Get the Maven tool.
        // ** NOTE: This 'mvn3.5.2' Maven tool must be configured
        // **       in the global configuration.
        mvnHome = tool 'mvn3.5.2'
    }
    stage('Build') {
        // Run the maven build
        if (isUnix()) {
            sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
        } else {
            bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
        }
    }
//    stage('Results') {
//        junit '**/target/surefire-reports/TEST-*.xml'
//        archive 'target/*.jar'
//    }
    post {
        always {
            //archive "target/**/*"
            archiveArtifacts artifacts: 'build/libs/**/*.jar', fingerprint: true
            junit 'target/surefire-reports/*.xml'
            echo 'Hello from staging branch'
        }
    }
}