pipeline {
    agent any
    environment {
        maven 'mvn3.5.2'
    }
    stages {
        stage('Preparation') { // for display purposes
            // Get some code from a GitHub repository
            git 'https://github.com/dannmatt/maven-simple-project.git'
        }
        stage('Build') {
            // Run the maven build
            if (isUnix()) {
                sh "mvn -Dmaven.test.failure.ignore clean package"
            } else {
                bat(/"mvn -Dmaven.test.failure.ignore clean package"/)
            }
        }
    //    stage('Results') {
    //        junit '**/target/surefire-reports/TEST-*.xml'
    //        archive 'target/*.jar'
    //    }
    }
    post {
        always {
            //archive "target/**/*"
            archiveArtifacts artifacts: 'build/libs/**/*.jar', fingerprint: true
            junit 'target/surefire-reports/*.xml'
        }
    }
}
